import { Platform, StyleSheet } from 'react-native';

import type { ThemeColors } from '../../theme/colors';

/** Визуальные токены админки — близко к skillo-fe admin-panel.css */
export const adminTokens = {
  radiusSm: 8,
  radiusMd: 12,
  radiusPill: 999,
  accentBlue: '#0A84FF',
  accentBlueMuted: 'rgba(10, 132, 255, 0.12)',
  accentBlueLine: 'rgba(10, 132, 255, 0.16)',
  dangerInk: '#d93654',
  dangerBg: 'rgba(220, 60, 60, 0.08)',
  successInk: '#248d5a',
  glassSurface: 'rgba(255, 255, 255, 0.92)',
};

export function adminStyles(colors: ThemeColors) {
  const cardShadow = Platform.select({
    ios: {
      shadowColor: '#0A84FF',
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.1,
      shadowRadius: 32,
    },
    android: { elevation: 4 },
    default: {},
  });

  return StyleSheet.create({
    safe: { flex: 1, backgroundColor: colors.surface },
    centered: { flex: 1, justifyContent: 'center', alignItems: 'center', gap: 12, padding: 24 },
    scroll: { padding: 20, paddingBottom: 40 },
    eyebrow: {
      fontSize: 10,
      fontWeight: '800',
      letterSpacing: 1.2,
      color: colors.ink3,
      textTransform: 'uppercase',
    },
    title: { fontSize: 24, fontWeight: '800', color: colors.ink, marginTop: 6 },
    lead: { fontSize: 15, color: colors.ink2, lineHeight: 22, marginTop: 8, marginBottom: 16 },
    card: {
      borderRadius: adminTokens.radiusMd,
      padding: 18,
      backgroundColor: colors.surface2,
      borderWidth: 1,
      borderColor: adminTokens.accentBlueLine,
      ...cardShadow,
    },
    cardTitle: { fontSize: 16, fontWeight: '700', color: colors.ink, marginBottom: 4 },
    cardSub: { fontSize: 13, color: colors.ink3, lineHeight: 18 },
    sectionTitle: {
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1,
      color: colors.ink3,
      textTransform: 'uppercase',
      marginTop: 24,
      marginBottom: 12,
    },
    errorBox: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 12,
      borderRadius: adminTokens.radiusSm,
      borderWidth: 1,
      borderColor: colors.danger,
      backgroundColor: `${colors.danger}11`,
      marginBottom: 12,
    },
    errorText: { flex: 1, color: colors.danger, fontSize: 14 },
    input: {
      minHeight: 48,
      borderWidth: 1,
      borderColor: adminTokens.accentBlueLine,
      borderRadius: adminTokens.radiusSm,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 16,
      color: colors.ink,
      backgroundColor: colors.surface,
    },
    inputLabel: {
      fontSize: 11,
      fontWeight: '700',
      letterSpacing: 0.8,
      color: colors.ink3,
      textTransform: 'uppercase',
      marginBottom: 6,
      marginTop: 12,
    },
    primaryBtn: {
      backgroundColor: adminTokens.accentBlue,
      borderRadius: adminTokens.radiusSm,
      paddingVertical: 14,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 48,
    },
    primaryBtnTxt: { color: '#fff', fontSize: 15, fontWeight: '700' },
    ghostBtn: {
      borderWidth: 1,
      borderColor: adminTokens.accentBlueLine,
      borderRadius: adminTokens.radiusSm,
      paddingVertical: 14,
      alignItems: 'center',
      backgroundColor: colors.surface,
    },
    ghostBtnTxt: { color: colors.ink, fontSize: 15, fontWeight: '600' },
    dangerBtn: {
      borderRadius: adminTokens.radiusPill,
      paddingVertical: 12,
      paddingHorizontal: 18,
      alignItems: 'center',
      backgroundColor: adminTokens.dangerBg,
    },
    dangerBtnTxt: { color: adminTokens.dangerInk, fontSize: 14, fontWeight: '700' },
    pill: {
      alignSelf: 'flex-start',
      paddingHorizontal: 10,
      paddingVertical: 4,
      borderRadius: adminTokens.radiusPill,
      borderWidth: 1,
      borderColor: adminTokens.accentBlueLine,
      backgroundColor: adminTokens.accentBlueMuted,
    },
    pillTxt: { fontSize: 11, fontWeight: '700', color: adminTokens.accentBlue },
    pillDanger: { borderColor: `${colors.danger}44`, backgroundColor: `${colors.danger}11` },
    pillDangerTxt: { color: colors.danger },
    navRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 14,
      padding: 16,
      borderRadius: adminTokens.radiusMd,
      borderWidth: 1,
      borderColor: adminTokens.accentBlueLine,
      backgroundColor: colors.surface2,
      marginBottom: 10,
      ...cardShadow,
    },
    navRowTitle: { fontSize: 16, fontWeight: '700', color: colors.ink },
    navRowSub: { fontSize: 13, color: colors.ink3, marginTop: 2 },
  });
}
